# create your drupal and postgres config here, based off the last assignment
version: '3.1'
services:
  
  drupal:
    image: drupal:8.2
    ports:
      - "8080:80"    
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql-pw
    secrets:
      - plsql-pw
    volumes:
      - drupal-data:/var/lib/postrgresql/data

secrets:
  psql-pw:
    external: true  

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
    